# Generated by Django 4.2.5 on 2023-10-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=100, verbose_name='Codigo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('rank', models.IntegerField(choices=[(1, 'Mala'), (2, 'Regular'), (3, 'Buena'), (4, 'Muy Buena'), (5, 'Excelente')], default=2, verbose_name='Calificacion')),
                ('image', models.ImageField(default='media/uploads/default_image.png', upload_to='media/uploads', verbose_name='Portada')),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('chapters', models.IntegerField(blank=True, default=None, null=True, verbose_name='Numero de Capitulos')),
                ('status', models.CharField(choices=[('P', 'Proximamente'), ('A', 'En Emision'), ('F', 'Finalizada')], max_length=1, verbose_name='Estado')),
                ('type', models.CharField(choices=[('TV', 'TV Show'), ('MOVIE', 'Pelicula'), ('GAME', 'Video Juegos')], max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'db_table': 'Series',
                'ordering': ['code', 'name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlsoNowAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='also_now_as', to='series.serie')),
            ],
            options={
                'verbose_name': 'Tambien conocido como',
                'verbose_name_plural': 'Tambien conocidos como',
                'db_table': 'also_now_as',
            },
        ),
    ]
