# Generated by Django 4.2.5 on 2023-10-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'genres',
            },
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['name', '-id'], 'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='serie',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Codigo'),
        ),
        migrations.CreateModel(
            name='SerieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_genres', to='series.genre')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_genres', to='series.serie')),
            ],
            options={
                'verbose_name': 'Genero por serie',
                'verbose_name_plural': 'Generos por series',
                'db_table': 'series_genres',
            },
        ),
    ]
