# Generated by Django 4.2.5 on 2023-10-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_genre_alter_serie_options_alter_serie_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-order', 'name', '-id'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.RemoveField(
            model_name='serie',
            name='rank',
        ),
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='calification',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Calificacion'),
        ),
        migrations.AddField(
            model_name='serie',
            name='imdb_calification',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='IMDB Calificacion'),
        ),
    ]
