# Generated by Django 4.2.5 on 2023-10-05 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_alter_genre_options_remove_serie_rank_genre_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.CharField(default='https://', max_length=200, verbose_name='URL')),
                ('url_format', models.CharField(default='https://', max_length=200, verbose_name='Formato')),
                ('order', models.IntegerField(blank=True, default=None, null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='series.serie')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'servers',
                'ordering': ['name'],
            },
        ),
    ]
