# Generated by Django 4.2.5 on 2023-10-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, choices=[('Secuela', 'Secuela'), ('Precuela', 'Precuela'), ('Historia Principal', 'Historia Principal'), ('Historia Paralela', 'Historia Paralela'), ('Resumen', 'Resumen')], default=None, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_relations', to='series.serie')),
                ('referenced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_relations_referenced', to='series.serie')),
            ],
            options={
                'verbose_name': 'Relacion entre series',
                'verbose_name_plural': 'Relaciones entre series',
                'db_table': 'series_relations',
            },
        ),
    ]
