# Generated by Django 4.2.5 on 2023-10-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_serierelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='pub_day_of_week',
            field=models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=None, null=True),
        ),
    ]
